import type { NextPage } from "next";
import Head from "next/head";
import { About } from "../sections/About";
import { Intro } from "../sections/Intro";
import { Navbar } from "../layouts/Navbar";
import { Experience } from "../sections/Experience";
import { Connect } from "../sections/Connect";
import { Projects } from "../sections/Projects";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Harshvardhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="h-screen overflow-scroll snap-y snap-mandatory scroll-smooth">
        <Intro />
        <About />
        <Projects />
        <Experience />
        <Connect />
      </main>
    </>
  );
};

export default Home;
